{% from "monitoring/map.jinja" import monitoring with context %}

sensuclient:
  image: registry.service.dsd.io/opguk/sensu-client:{{monitoring.version.opg_docker_monitoring}}
  log_driver: syslog
  ports:
    - 3030:3030
  env_file:
{%  set env_files = [] %}
{%  if salt['pillar.get']('services:monitoring-client:env_files') is defined %}
{%    for env_name in salt['pillar.get']('services:monitoring-client:env_files') %}
{%      set env_files = env_files +  [env_name] %}
{%    endfor %}
{%  elif salt['pillar.get']('services:monitoring-client:extra') is defined %}
{%    for env_name in salt['pillar.get']('services:monitoring-client:extra') %}
{%      set env_files = env_files + [env_name|replace('_' + grains['opg_role'], '')] %}
{%    endfor %}
{%  else %}
   - ./sensuclient.env
{%    if salt['pillar.get']('monitoring:client:checksbase:env') %}
{%      set env_files = env_files + ['checksbase'] %}
{%    endif %}
{%    if salt['pillar.get']('monitoring:client:checksrole:env') %}
{%      set env_files = env_files + ['checksrole'] %}
{%    endif %}
{%  endif %}
{% for env_file in env_files %}
   - ./{{ env_file }}.env
{% endfor %}
